{% set name = "treeinterpreter" %}
{% set version = "0.2.3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: da5c24f802f7d072bc457b6e4b289d5ee41961ce33437e8dc439a2cfd9c6d994

build:
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps --no-build-isolation -vv

requirements:
  host:
    - pip
    - setuptools
    - wheel
    - python
  run:
    - python
    - numpy
    - scikit-learn >=0.17

test:
  imports:
    - treeinterpreter
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/andosa/treeinterpreter
  summary: Package for interpreting scikit-learn's decision tree and random forest predictions.
  description: |
    Package for interpreting scikit-learn's decision tree and random forest predictions. 
    Allows decomposing each prediction into bias and feature contribution components.
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  doc_url: https://github.com/andosa/treeinterpreter/blob/master/README.rst
  dev_url: https://github.com/andosa/treeinterpreter

extra:
  recipe-maintainers:
    - philip-khor
